In [1]:
import numpy as np

In [2]:
mat = np.arange(1,25).reshape(6,4)

In [3]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [36]:
mat [[2,3]]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
mat [[2,3],1:3]

array([[10, 11],
       [14, 15]])

In [49]:
mat [[1, 2, 3, 4, 5]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [53]:
mat [[1, 2, 3, 4, 5], 1:]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20],
       [22, 23, 24]])

In [54]:
mat[[2,4]]

array([[ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [93]:
mat[[2,4], 1:]

array([[10, 11, 12],
       [18, 19, 20]])

In [103]:
mat[[2,4], 1::2]

array([[10, 12],
       [18, 20]])

In [83]:
mat[[0,2,4]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [91]:
mat[[0,2,4],::3]

array([[ 1,  4],
       [ 9, 12],
       [17, 20]])

In [106]:
mat[[0,3], 1:3]

array([[ 2,  3],
       [14, 15]])

In [107]:
mat[[1,3,4]]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [113]:
mat[[1,3,4], : :3]

array([[ 5,  8],
       [13, 16],
       [17, 20]])

In [114]:
#BOOLEAN

In [126]:
rand_num = np.random.uniform(1000,10000,200)

In [128]:
rand_num

array([6045.33426211, 6873.07525206, 4922.3992786 , 4464.91316352,
       8882.58429423, 2326.02452991, 7739.06215012, 4168.4892213 ,
       8547.71620327, 7214.56747815, 7627.79564272, 7861.50801417,
       7815.35160021, 1663.27954218, 4757.65052525, 9147.05838027,
       8714.78948702, 8223.1235043 , 3664.77568859, 8554.86141432,
       5104.4892766 , 8564.53460845, 8856.44334064, 7758.37209431,
       1742.62332093, 6403.52982283, 1006.68355903, 3484.04624264,
       3815.31294858, 1451.15334771, 2627.36090695, 5508.33404188,
       5777.87990521, 1970.35332398, 3178.42126524, 5165.57171854,
       1308.69488778, 1222.2874228 , 9856.34728549, 3373.908447  ,
       4334.8637683 , 6953.44040048, 2165.0252939 , 9986.64554771,
       6212.89475459, 9897.75912748, 2572.69249466, 3093.54405167,
       3219.00467962, 7220.11795528, 1535.19479262, 7658.73931691,
       3457.07276077, 8893.64994409, 4486.92282547, 7164.23828044,
       6847.42365518, 1909.01446245, 8490.76529192, 4700.00782

In [149]:
cheap = (1000-2499)
fair = (2500-4999) 
expensive = (5000-10000)

In [164]:
 rand_num == (1000-2499)
   
    


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [165]:
rand_num == (2500-4999)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [167]:
rand_num == (5000-10000)

True

In [186]:
t_cheap=np.add(1000, 2499)


In [184]:
t_cheap

3499

In [188]:
t_fair =np.add(2500,4999)

In [189]:
t_fair

7499

In [190]:
t_expensive =np.add(5000,10000)

In [191]:
t_expensive

15000

In [205]:
Total =  3499 + 7499 + 15000

In [206]:
Total

25998

In [207]:
TOTAL = t_expensive + t_fair +t_cheap

In [208]:
TOTAL

array([[22499.]])